import type { User, Task } from './types';

export const mockUsers: User[] = [
    { userId: 'user-1', displayName: 'Alex Doe', email: 'user@focusflow.com', role: 'Admin', status: 'Active', creationDate: new Date('2023-01-15T09:00:00Z') },
    { userId: 'user-2', displayName: 'Jane Smith', email: 'jane@example.com', role: 'User', status: 'Active', creationDate: new Date('2023-02-10T11:00:00Z') },
    { userId: 'user-3', displayName: 'Sam Wilson', email: 'sam@example.com', role: 'User', status: 'Invited', creationDate: new Date('2023-03-20T14:30:00Z') },
];


export const mockTasks: Task[] = [
  {
    taskId: 'task-1',
    userId: 'user-1',
    title: 'Launch Q3 Marketing Campaign',
    description: 'Coordinate all efforts for the new product launch.',
    isCompleted: false,
    isHighImpact: true,
    dueDate: new Date(new Date().setDate(new Date().getDate() + 10)),
    parentId: null,
    pomodoroSessions: 5,
    creationDate: new Date('2023-10-01T10:00:00Z'),
  },
  {
    taskId: 'task-2',
    userId: 'user-1',
    title: 'Develop Landing Page',
    isCompleted: true,
    isHighImpact: false,
    dueDate: new Date(new Date().setDate(new Date().getDate() - 2)),
    parentId: 'task-1',
    pomodoroSessions: 8,
    creationDate: new Date('2023-10-02T11:00:00Z'),
    completionDate: new Date('2023-10-08T16:00:00Z'),
  },
  {
    taskId: 'task-3',
    userId: 'user-1',
    title: 'Create Ad Copy',
    isCompleted: false,
    isHighImpact: true,
    dueDate: new Date(new Date().setDate(new Date().getDate() + 5)),
    parentId: 'task-1',
    pomodoroSessions: 2,
    creationDate: new Date('2023-10-03T14:00:00Z'),
  },
  {
    taskId: 'task-4',
    userId: 'user-1',
    title: 'Design Graphics',
    isCompleted: false,
    isHighImpact: false,
    dueDate: new Date(new Date().setDate(new Date().getDate() + 3)),
    parentId: 'task-3',
    pomodoroSessions: 0,
    creationDate: new Date('2023-10-04T09:00:00Z'),
  },
  {
    taskId: 'task-5',
    userId: 'user-1',
    title: 'Organize Personal Finances',
    description: 'Review budget and investments for the year.',
    isCompleted: false,
    isHighImpact: false,
    dueDate: new Date(new Date().setDate(new Date().getDate() + 7)),
    parentId: null,
    pomodoroSessions: 1,
    creationDate: new Date('2023-10-05T18:00:00Z'),
  },
  {
    taskId: 'task-6',
    userId: 'user-1',
    title: 'Pay monthly bills',
    isCompleted: true,
    isHighImpact: false,
    dueDate: new Date(new Date().setDate(new Date().getDate() - 5)),
    parentId: 'task-5',
    pomodoroSessions: 1,
    creationDate: new Date('2023-10-06T12:00:00Z'),
    completionDate: new Date('2023-10-07T10:00:00Z'),
  },
  {
    taskId: 'task-7',
    userId: 'user-1',
    title: 'Refactor Authentication Service',
    isCompleted: false,
    isHighImpact: true,
    dueDate: new Date(new Date().setDate(new Date().getDate() + 20)),
    parentId: null,
    pomodoroSessions: 0,
    creationDate: new Date('2023-10-10T15:00:00Z'),
  },
];
